name: Solve Captcha with Python and Google Lens

on:
  workflow_dispatch:
    inputs:
      captcha_image:
        description: 'Captcha image base64 encoded'
        required: true
        type: string

jobs:
  solve-captcha:
    runs-on: ubuntu-latest
    concurrency:
      group: captcha-solving
      cancel-in-progress: false  # Prevent cancellation of an ongoing workflow

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask selenium flask-cors

    - name: Run Python captcha solving server
      run: |
        nohup python cap_python_code.py &  # Run the server in the background

    - name: Trigger the Flask server with captcha image
      run: |
        curl -X POST http://127.0.0.1:5000/solve_captcha \
        -H "Content-Type: application/json" \
        -d '{"captcha_image": "${{ github.event.inputs.captcha_image }}"}'
