name: Solve Captcha with Python and Google Lens

on:
  workflow_dispatch:
    inputs:
      captcha_image:
        description: 'Captcha image base64 encoded'
        required: true
        type: string

jobs:
  solve-captcha:
    runs-on: ubuntu-latest
    concurrency:
      group: captcha-solving
      cancel-in-progress: false  # Do not cancel ongoing workflows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask selenium flask-cors

    - name: Run Python captcha solving script
      run: |
        python cap_python_code.py
      env:
        CAPTURE_IMAGE: ${{ github.event.inputs.captcha_image }}

    - name: Upload result to GitHub (optional)
      run: |
        echo "Recognized captcha text: ${CAPTURE_TEXT}"
